<?php

return [
    'export' => [
        'max_rows' => 50000,
    ],

    'categories' => [
        'sales' => ['label' => 'Sales & POS', 'icon' => 'fa-cash-register'],
        'inventory' => ['label' => 'Inventory', 'icon' => 'fa-boxes-stacked'],
        'procurement' => ['label' => 'Procurement', 'icon' => 'fa-folder-open'],
        'transfers' => ['label' => 'Transfers', 'icon' => 'fa-right-left'],
        'returns' => ['label' => 'Returns', 'icon' => 'fa-rotate-left'],
        'receivables' => ['label' => 'Fleet & AR', 'icon' => 'fa-file-invoice-dollar'],
        'finance' => ['label' => 'Finance', 'icon' => 'fa-coins'],
        'catalog' => ['label' => 'Catalog', 'icon' => 'fa-tags'],
    ],

    'reports' => [
        // --- R0 live ---
        'sales' => [
            'label' => 'Sales Summary',
            'description' => 'Revenue, tickets, daily trend, top sellers with vehicle fitment',
            'category' => 'sales',
            'query' => \App\Services\Reports\SalesReportQuery::class,
            'status' => 'live',
            'scopes' => ['shop', 'global'],
            'export' => true,
            'filters' => ['shop', 'preset', 'dates'],
        ],
        'inventory' => [
            'label' => 'Inventory Summary',
            'description' => 'Valuation by location, low stock in catalog units, movements',
            'category' => 'inventory',
            'query' => \App\Services\Reports\InventoryReportQuery::class,
            'status' => 'live',
            'scopes' => ['shop', 'warehouse', 'global'],
            'export' => true,
            'filters' => ['shop', 'warehouse', 'preset', 'dates'],
        ],
        'procurement' => [
            'label' => 'Procurement Summary',
            'description' => 'Quotation series, purchase orders, goods receipts',
            'category' => 'procurement',
            'query' => \App\Services\Reports\ProcurementReportQuery::class,
            'status' => 'live',
            'scopes' => ['global'],
            'export' => true,
            'filters' => ['preset', 'dates'],
        ],
        'transfers' => [
            'label' => 'Transfer Activity',
            'description' => 'Transfer requests and dispatch pipeline',
            'category' => 'transfers',
            'query' => \App\Services\Reports\TransferReportQuery::class,
            'status' => 'live',
            'scopes' => ['shop', 'global'],
            'export' => true,
            'filters' => ['shop', 'preset', 'dates'],
        ],
        'financial' => [
            'label' => 'Financial Summary',
            'description' => 'Net revenue, refunds, payment mix (operational)',
            'category' => 'finance',
            'query' => \App\Services\Reports\FinancialReportQuery::class,
            'status' => 'live',
            'scopes' => ['shop', 'global'],
            'export' => true,
            'filters' => ['shop', 'preset', 'dates'],
        ],

        // --- R1 Sales ---
        'sales-by-shop' => [
            'label' => 'Sales by Shop',
            'description' => 'Compare revenue and tickets across shops',
            'category' => 'sales',
            'query' => \App\Services\Reports\SalesByShopReportQuery::class,
            'status' => 'live',
            'scopes' => ['shop', 'global'],
            'export' => true,
            'filters' => ['shop', 'preset', 'dates'],
        ],
        'sales-by-cashier' => [
            'label' => 'Sales by Cashier',
            'description' => 'Revenue and tickets per attendant',
            'category' => 'sales',
            'query' => \App\Services\Reports\SalesByCashierReportQuery::class,
            'status' => 'live',
            'scopes' => ['shop', 'global'],
            'export' => true,
            'filters' => ['shop', 'preset', 'dates'],
        ],
        'payment-method-mix' => [
            'label' => 'Payment Method Mix',
            'description' => 'Cash, M-Pesa, card, and other payments',
            'category' => 'sales',
            'query' => \App\Services\Reports\PaymentMethodMixReportQuery::class,
            'status' => 'live',
            'scopes' => ['shop', 'global'],
            'export' => true,
            'filters' => ['shop', 'preset', 'dates'],
        ],
        'on-account-vs-cash' => [
            'label' => 'On-Account vs Cash',
            'description' => 'Retail, fleet credit, and reinstatement sales split',
            'category' => 'sales',
            'query' => \App\Services\Reports\OnAccountVsCashReportQuery::class,
            'status' => 'live',
            'scopes' => ['shop', 'global'],
            'export' => true,
            'filters' => ['shop', 'preset', 'dates'],
        ],
        'held-orders' => [
            'label' => 'Held Orders',
            'description' => 'Open held tickets and value at risk',
            'category' => 'sales',
            'query' => \App\Services\Reports\HeldOrdersReportQuery::class,
            'status' => 'live',
            'scopes' => ['shop', 'global'],
            'export' => true,
            'filters' => ['shop'],
        ],
        'reversed-sales' => [
            'label' => 'Reversed Sales',
            'description' => 'Sales reversed in the selected period',
            'category' => 'sales',
            'query' => \App\Services\Reports\ReversedSalesReportQuery::class,
            'status' => 'live',
            'scopes' => ['shop', 'global'],
            'export' => true,
            'filters' => ['shop', 'preset', 'dates'],
        ],
        'gross-margin' => [
            'label' => 'Gross Margin',
            'description' => 'Revenue minus COGS using captured line costs',
            'category' => 'sales',
            'query' => \App\Services\Reports\GrossMarginReportQuery::class,
            'status' => 'live',
            'scopes' => ['shop', 'global'],
            'export' => true,
            'filters' => ['shop', 'preset', 'dates'],
        ],
        'sales-by-category' => [
            'label' => 'Sales by Category',
            'description' => 'Revenue mix by product category',
            'category' => 'sales',
            'query' => \App\Services\Reports\SalesByCategoryReportQuery::class,
            'status' => 'live',
            'scopes' => ['shop', 'global'],
            'export' => true,
            'filters' => ['shop', 'preset', 'dates'],
        ],

        // --- R1 Inventory ---
        'stock-movements' => [
            'label' => 'Stock Movements',
            'description' => 'Ledger entries grouped by transaction type',
            'category' => 'inventory',
            'query' => \App\Services\Reports\StockMovementsReportQuery::class,
            'status' => 'live',
            'scopes' => ['shop', 'warehouse', 'global'],
            'export' => true,
            'filters' => ['shop', 'warehouse', 'preset', 'dates'],
        ],
        'stock-ledger' => [
            'label' => 'Stock Ledger Detail',
            'description' => 'Full exportable movement journal',
            'category' => 'inventory',
            'query' => \App\Services\Reports\StockLedgerDetailReportQuery::class,
            'status' => 'live',
            'scopes' => ['shop', 'warehouse', 'global'],
            'export' => true,
            'filters' => ['shop', 'warehouse', 'preset', 'dates'],
        ],
        'stock-adjustments' => [
            'label' => 'Stock Adjustments',
            'description' => 'Approved count adjustments in period',
            'category' => 'inventory',
            'query' => \App\Services\Reports\StockAdjustmentsReportQuery::class,
            'status' => 'live',
            'scopes' => ['shop', 'warehouse', 'global'],
            'export' => true,
            'filters' => ['shop', 'warehouse', 'preset', 'dates'],
        ],
        'reorder-worksheet' => [
            'label' => 'Reorder Worksheet',
            'description' => 'SKUs at or below reorder level (catalog units)',
            'category' => 'inventory',
            'query' => \App\Services\Reports\ReorderWorksheetReportQuery::class,
            'status' => 'live',
            'scopes' => ['shop', 'warehouse', 'global'],
            'export' => true,
            'filters' => ['shop', 'warehouse'],
        ],

        // --- R1 Procurement ---
        'open-purchase-orders' => [
            'label' => 'Open Purchase Orders',
            'description' => 'PO lines with remaining quantity to receive',
            'category' => 'procurement',
            'query' => \App\Services\Reports\OpenPurchaseOrdersReportQuery::class,
            'status' => 'live',
            'scopes' => ['global'],
            'export' => true,
            'filters' => ['supplier'],
        ],
        'po-grn-variance' => [
            'label' => 'PO vs GRN Variance',
            'description' => 'Ordered vs received quantities',
            'category' => 'procurement',
            'query' => \App\Services\Reports\PoGrnVarianceReportQuery::class,
            'status' => 'live',
            'scopes' => ['global'],
            'export' => true,
            'filters' => ['supplier', 'preset', 'dates'],
        ],
        'supplier-payment-register' => [
            'label' => 'Supplier Payment Register',
            'description' => 'Payments and voids in period',
            'category' => 'procurement',
            'query' => \App\Services\Reports\SupplierPaymentRegisterReportQuery::class,
            'status' => 'live',
            'scopes' => ['global'],
            'export' => true,
            'filters' => ['supplier', 'preset', 'dates'],
        ],

        // --- R1 Transfers ---
        'stock-transfer-detail' => [
            'label' => 'Stock Transfer Detail',
            'description' => 'Dispatched vs received quantities per transfer',
            'category' => 'transfers',
            'query' => \App\Services\Reports\StockTransferDetailReportQuery::class,
            'status' => 'live',
            'scopes' => ['shop', 'warehouse', 'global'],
            'export' => true,
            'filters' => ['shop', 'warehouse', 'preset', 'dates'],
        ],
        'transfer-fill-rate' => [
            'label' => 'Transfer Fill Rate',
            'description' => 'Request acceptance and fulfilment rates',
            'category' => 'transfers',
            'query' => \App\Services\Reports\TransferFillRateReportQuery::class,
            'status' => 'live',
            'scopes' => ['shop', 'global'],
            'export' => true,
            'filters' => ['shop', 'preset', 'dates'],
        ],
        'in-transit-aging' => [
            'label' => 'In-Transit Aging',
            'description' => 'Transfers awaiting receipt by age',
            'category' => 'transfers',
            'query' => \App\Services\Reports\InTransitAgingReportQuery::class,
            'status' => 'live',
            'scopes' => ['shop', 'warehouse', 'global'],
            'export' => true,
            'filters' => ['shop', 'warehouse'],
        ],

        // --- R1 Returns ---
        'customer-returns' => [
            'label' => 'Customer Returns',
            'description' => 'Refunds, reasons, and products returned',
            'category' => 'returns',
            'query' => \App\Services\Reports\CustomerReturnsReportQuery::class,
            'status' => 'live',
            'scopes' => ['shop', 'global'],
            'export' => true,
            'filters' => ['shop', 'preset', 'dates'],
        ],
        'supplier-returns' => [
            'label' => 'Supplier Returns',
            'description' => 'Stock returned to suppliers from warehouses',
            'category' => 'returns',
            'query' => \App\Services\Reports\SupplierReturnsReportQuery::class,
            'status' => 'live',
            'scopes' => ['warehouse', 'global'],
            'export' => true,
            'filters' => ['warehouse', 'preset', 'dates'],
        ],

        // --- R1 AR ---
        'ar-aging' => [
            'label' => 'AR Aging',
            'description' => 'Outstanding invoices by age bucket',
            'category' => 'receivables',
            'query' => \App\Services\Reports\ArAgingReportQuery::class,
            'status' => 'live',
            'scopes' => ['global'],
            'export' => true,
            'filters' => [],
        ],
        'overdue-invoices' => [
            'label' => 'Overdue Invoices',
            'description' => 'Past-due fleet invoices',
            'category' => 'receivables',
            'query' => \App\Services\Reports\OverdueInvoicesReportQuery::class,
            'status' => 'live',
            'scopes' => ['global'],
            'export' => true,
            'filters' => [],
        ],

        // --- Catalog ---
        'product-master' => [
            'label' => 'Product Master Export',
            'description' => 'Full SKU list with category and vehicle fitment',
            'category' => 'catalog',
            'query' => \App\Services\Reports\ProductMasterReportQuery::class,
            'status' => 'live',
            'scopes' => ['global'],
            'export' => true,
            'filters' => [],
        ],
    ],
];
